#!/usr/bin/env bash
set -euo pipefail

# Format staged Go files with goimports and include the results in this commit.
go_files=$(git diff --cached --name-only --diff-filter=ACM -- '*.go')

if [ -n "$go_files" ]; then
  (cd server && golangci-lint fmt ./...)
  git add -- $go_files

  # Test and lint the server module to catch errors before committing.
  (
    cd server
    go test ./...
    golangci-lint run ./...
  )
fi

# Auto-fix and format staged Dart files and include the results in this commit.
dart_files=$(git diff --cached --name-only --diff-filter=ACM -- '*.dart')

if [ -n "$dart_files" ]; then
  fvm dart fix --apply .
  fvm dart format $dart_files
  git add -- $dart_files

  # Aanalyze the client module to catch errors before committing.
  (
    cd client
    fvm flutter analyze
  )
fi

# Format staged JSON, YAML, and Markdown files with prettier and include the results in this commit.
prettier_files=$(git diff --cached --name-only --diff-filter=ACM -- '*.json' '*.yaml' '*.yml' '*.md')

if [ -n "$prettier_files" ]; then
  prettier -w $prettier_files
  git add -- $prettier_files
fi
