// Mocks generated by Mockito 5.4.6 from annotations
// in paperdoll/test/features/auth/auth_screens_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;

import 'package:device_info_plus/device_info_plus.dart' as _i13;
import 'package:device_info_plus/src/model/android_device_info.dart' as _i2;
import 'package:device_info_plus/src/model/ios_device_info.dart' as _i3;
import 'package:device_info_plus/src/model/linux_device_info.dart' as _i4;
import 'package:device_info_plus/src/model/macos_device_info.dart' as _i6;
import 'package:device_info_plus/src/model/web_browser_info.dart' as _i5;
import 'package:device_info_plus/src/model/windows_device_info.dart' as _i7;
import 'package:device_info_plus_platform_interface/device_info_plus_platform_interface.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:paperdoll/features/auth/data/token_storage.dart' as _i9;
import 'package:paperdoll/features/auth/domain/auth_repository.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAndroidDeviceInfo_0 extends _i1.SmartFake
    implements _i2.AndroidDeviceInfo {
  _FakeAndroidDeviceInfo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIosDeviceInfo_1 extends _i1.SmartFake implements _i3.IosDeviceInfo {
  _FakeIosDeviceInfo_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLinuxDeviceInfo_2 extends _i1.SmartFake
    implements _i4.LinuxDeviceInfo {
  _FakeLinuxDeviceInfo_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebBrowserInfo_3 extends _i1.SmartFake
    implements _i5.WebBrowserInfo {
  _FakeWebBrowserInfo_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMacOsDeviceInfo_4 extends _i1.SmartFake
    implements _i6.MacOsDeviceInfo {
  _FakeMacOsDeviceInfo_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWindowsDeviceInfo_5 extends _i1.SmartFake
    implements _i7.WindowsDeviceInfo {
  _FakeWindowsDeviceInfo_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseDeviceInfo_6 extends _i1.SmartFake
    implements _i8.BaseDeviceInfo {
  _FakeBaseDeviceInfo_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TokenStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockTokenStorage extends _i1.Mock implements _i9.TokenStorage {
  MockTokenStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<String?> read() =>
      (super.noSuchMethod(
            Invocation.method(#read, []),
            returnValue: _i10.Future<String?>.value(),
          )
          as _i10.Future<String?>);

  @override
  _i10.Future<void> write(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#write, [token]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> delete() =>
      (super.noSuchMethod(
            Invocation.method(#delete, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i11.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<String> signUp({
    required String? email,
    required String? password,
    required String? device,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #password: password,
              #device: device,
            }),
            returnValue: _i10.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#signUp, [], {
                  #email: email,
                  #password: password,
                  #device: device,
                }),
              ),
            ),
          )
          as _i10.Future<String>);

  @override
  _i10.Future<String> signIn({
    required String? email,
    required String? password,
    required String? device,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
              #device: device,
            }),
            returnValue: _i10.Future<String>.value(
              _i12.dummyValue<String>(
                this,
                Invocation.method(#signIn, [], {
                  #email: email,
                  #password: password,
                  #device: device,
                }),
              ),
            ),
          )
          as _i10.Future<String>);
}

/// A class which mocks [DeviceInfoPlugin].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceInfoPlugin extends _i1.Mock implements _i13.DeviceInfoPlugin {
  MockDeviceInfoPlugin() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i2.AndroidDeviceInfo> get androidInfo =>
      (super.noSuchMethod(
            Invocation.getter(#androidInfo),
            returnValue: _i10.Future<_i2.AndroidDeviceInfo>.value(
              _FakeAndroidDeviceInfo_0(this, Invocation.getter(#androidInfo)),
            ),
          )
          as _i10.Future<_i2.AndroidDeviceInfo>);

  @override
  _i10.Future<_i3.IosDeviceInfo> get iosInfo =>
      (super.noSuchMethod(
            Invocation.getter(#iosInfo),
            returnValue: _i10.Future<_i3.IosDeviceInfo>.value(
              _FakeIosDeviceInfo_1(this, Invocation.getter(#iosInfo)),
            ),
          )
          as _i10.Future<_i3.IosDeviceInfo>);

  @override
  _i10.Future<_i4.LinuxDeviceInfo> get linuxInfo =>
      (super.noSuchMethod(
            Invocation.getter(#linuxInfo),
            returnValue: _i10.Future<_i4.LinuxDeviceInfo>.value(
              _FakeLinuxDeviceInfo_2(this, Invocation.getter(#linuxInfo)),
            ),
          )
          as _i10.Future<_i4.LinuxDeviceInfo>);

  @override
  _i10.Future<_i5.WebBrowserInfo> get webBrowserInfo =>
      (super.noSuchMethod(
            Invocation.getter(#webBrowserInfo),
            returnValue: _i10.Future<_i5.WebBrowserInfo>.value(
              _FakeWebBrowserInfo_3(this, Invocation.getter(#webBrowserInfo)),
            ),
          )
          as _i10.Future<_i5.WebBrowserInfo>);

  @override
  _i10.Future<_i6.MacOsDeviceInfo> get macOsInfo =>
      (super.noSuchMethod(
            Invocation.getter(#macOsInfo),
            returnValue: _i10.Future<_i6.MacOsDeviceInfo>.value(
              _FakeMacOsDeviceInfo_4(this, Invocation.getter(#macOsInfo)),
            ),
          )
          as _i10.Future<_i6.MacOsDeviceInfo>);

  @override
  _i10.Future<_i7.WindowsDeviceInfo> get windowsInfo =>
      (super.noSuchMethod(
            Invocation.getter(#windowsInfo),
            returnValue: _i10.Future<_i7.WindowsDeviceInfo>.value(
              _FakeWindowsDeviceInfo_5(this, Invocation.getter(#windowsInfo)),
            ),
          )
          as _i10.Future<_i7.WindowsDeviceInfo>);

  @override
  _i10.Future<_i8.BaseDeviceInfo> get deviceInfo =>
      (super.noSuchMethod(
            Invocation.getter(#deviceInfo),
            returnValue: _i10.Future<_i8.BaseDeviceInfo>.value(
              _FakeBaseDeviceInfo_6(this, Invocation.getter(#deviceInfo)),
            ),
          )
          as _i10.Future<_i8.BaseDeviceInfo>);
}
